import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import { TimeButton } from "./components/TimeButton";
import { TimeProvider } from "./components/TimeContext";
import { ToastWrapper } from "./components/ToastWrapper";
import { UserProvider } from "./components/UserContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
					rel="stylesheet"
					integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
					crossOrigin="anonymous"
				/>
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
				/>
			</head>
			<UserProvider>
				<TimeProvider>
					<body className={`${inter.className} m-0 p-0`}>
						<ToastWrapper />
						{children}
						<TimeButton />
					</body>
				</TimeProvider>
			</UserProvider>
			<Script
				src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
				integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
				crossOrigin="anonymous"
				strategy="afterInteractive"
			/>
		</html>
	);
}
